// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_dosO4FayefRvTt6FuT0gZsVpwKfmGWg',
    appId: '1:614622689981:web:c6afcf576d9c2c1b0a15d4',
    messagingSenderId: '614622689981',
    projectId: 'crudfirebase-1ab03',
    authDomain: 'crudfirebase-1ab03.firebaseapp.com',
    storageBucket: 'crudfirebase-1ab03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR59F93bmlADa-Axm-qbVkImc1bF6NyZQ',
    appId: '1:614622689981:android:7de8e1c4a3d92edc0a15d4',
    messagingSenderId: '614622689981',
    projectId: 'crudfirebase-1ab03',
    storageBucket: 'crudfirebase-1ab03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu5xaco-kvCaIf4X9Zt8beCK3GYUZLS2Y',
    appId: '1:614622689981:ios:0d6b1779769d50fd0a15d4',
    messagingSenderId: '614622689981',
    projectId: 'crudfirebase-1ab03',
    storageBucket: 'crudfirebase-1ab03.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu5xaco-kvCaIf4X9Zt8beCK3GYUZLS2Y',
    appId: '1:614622689981:ios:0d6b1779769d50fd0a15d4',
    messagingSenderId: '614622689981',
    projectId: 'crudfirebase-1ab03',
    storageBucket: 'crudfirebase-1ab03.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_dosO4FayefRvTt6FuT0gZsVpwKfmGWg',
    appId: '1:614622689981:web:c5a2f32b1839fe9f0a15d4',
    messagingSenderId: '614622689981',
    projectId: 'crudfirebase-1ab03',
    authDomain: 'crudfirebase-1ab03.firebaseapp.com',
    storageBucket: 'crudfirebase-1ab03.firebasestorage.app',
  );
}
